'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const demo = require('../article-demo.cjs');
const { buildSeo, getArticlePath, renderArticleMain } = require('../server/_article-render');

const root = path.resolve(__dirname, '..');
const template = fs.readFileSync(path.join(root, 'article.html'), 'utf8');
const home = fs.readFileSync(path.join(root, 'home.template.html'), 'utf8');
const news = fs.readFileSync(path.join(root, 'news.template.html'), 'utf8');
const styles = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const behavior = fs.readFileSync(path.join(root, 'article.js'), 'utf8');
const rendered = renderArticleMain(demo);
const multiParagraphDemo = structuredClone(demo);
multiParagraphDemo.content.blocks.splice(1, 0, { type: 'paragraph', text: 'A second introductory paragraph before the first article section.' });
const multiParagraphRendered = renderArticleMain(multiParagraphDemo);
const legacyDemo = structuredClone(demo);
legacyDemo.authorImage = '';
delete legacyDemo.content.sidebarCtaTitle;
delete legacyDemo.content.sidebarCtaDescription;
delete legacyDemo.content.sidebarCtaLabel;
delete legacyDemo.content.sidebarCtaUrl;
const legacyRendered = renderArticleMain(legacyDemo);
const seo = buildSeo(demo);

assert.match(template, /class="article-page"/);
assert.match(template, /<!-- ARTICLE_SEO -->/);
assert.match(template, /<!-- ARTICLE_MAIN -->/);
assert.match(rendered, /How Car Dealerships Can/);
assert.match(rendered, /Founder of Studio 17/);
assert.match(rendered, /7 minutes/);
assert.match(rendered, /datetime="2026-06-22"/);
assert.match(rendered, /class="article-cover reveal"/);
assert.ok(rendered.indexOf('class="article-lead"') < rendered.indexOf('class="article-cover reveal"'));
assert.ok(rendered.indexOf('class="article-cover reveal"') < rendered.indexOf('<section id="the-first-visit-often-happens-online"'));
assert.ok(multiParagraphRendered.indexOf('A second introductory paragraph') < multiParagraphRendered.indexOf('class="article-cover reveal"'));
assert.ok(multiParagraphRendered.indexOf('class="article-cover reveal"') < multiParagraphRendered.indexOf('<section id="the-first-visit-often-happens-online"'));
assert.match(rendered, /class="shell article-layout has-related"/);
assert.match(rendered, /class="article-meta-author"/);
assert.match(rendered, /class="article-author-image"/);
assert.match(legacyRendered, /class="article-author-fallback"/);
assert.match(rendered, /class="article-toc" data-article-toc open/);
assert.match(rendered, /class="article-related-rail"/);
assert.match(rendered, /class="article-rail-cta"/);
assert.equal((rendered.match(/class="article-rail-card"/g) || []).length, 3);
assert.equal((rendered.match(/class="news-card"/g) || []).length, 4);
assert.match(rendered, /data-related-carousel/);
assert.match(rendered, /data-related-prev/);
assert.match(rendered, /data-related-next/);
assert.match(rendered, /Valuable <span>related information<\/span>/);
assert.match(rendered, /class="triangle-controls article-related-controls"/);
assert.match(rendered, /class="article-inline-image"/);
assert.match(rendered, /class="article-table-wrap"[^>]*role="region"[^>]*tabindex="0"/);
assert.match(rendered, /<th scope="col">Stage<\/th>/);
assert.match(rendered, /<td>Measure response time<\/td>/);
assert.match(rendered, /class="article-cta"/);
assert.match(seo, /"@type":"Article"/);
assert.match(seo, /"author":\{"@type":"Person","name":"Hugo Filipe","image":"https:\/\/www\.studio17\.world\/Images\/About_heroimage\.webp"\}/);
assert.equal(getArticlePath({ slug: 'useful-guide', category: 'Insight' }, 'en'), '/insights/useful-guide');
assert.equal(getArticlePath({ slug: 'client-result', category: 'Case Study' }, 'en'), '/case-studies/client-result');
assert.equal(getArticlePath({ slug: 'company-update', category: 'News' }, 'el'), '/news/company-update?lang=el');
assert.match(seo, /https:\/\/www\.studio17\.world\/case-studies\/how-car-dealerships-can-increase-monthly-sales/);
assert.match(seo, /name="robots" content="index,follow,max-image-preview:large"/);
assert.match(seo, /og:image" content="https:\/\/www\.studio17\.world\/Images\/news-partnership\.webp"/);
assert.doesNotMatch(seo, /og:image" content="https:\/\/www\.studio17\.world\/Images\/case-automotive\.webp"/);
assert.match(home, /data-article-feed="home"/);
assert.match(home, /article-feed\.js/);
assert.match(news, /class="news-page"/);
assert.match(news, /data-article-feed="archive"/);
assert.match(styles, /\.article-hero/);
assert.match(styles, /\.article-layout\.has-related \{[^}]*grid-template-columns:[^}]*minmax\(0,720px\)[^}]*minmax\(240px,300px\)/);
assert.match(styles, /\.article-cover img \{[^}]*aspect-ratio: 16\/9/);
assert.doesNotMatch(styles, /\.article-cover \{ display: none; \}/);
assert.match(styles, /\.article-table-wrap \{[^}]*overflow-x: auto/);
assert.match(styles, /\.article-rail-cta/);
assert.match(styles, /\.article-rail-cta \.solid-button > span \{[^}]*display: grid;[^}]*flex: 0 0 30px;[^}]*place-items: center;/);
assert.match(styles, /\.article-related-track/);
assert.match(styles, /html\[dir="rtl"\] \.article-table \{ text-align: right; \}/);
assert.match(styles, /\.news-archive-grid/);
assert.match(behavior, /data-article-progress/);
assert.match(behavior, /data-article-toc/);
assert.match(behavior, /matchMedia\('\(max-width: 800px\)'\)/);
assert.match(behavior, /navigator\.share/);
assert.match(behavior, /__STUDIO17_ARTICLE_LANGUAGES__/);
assert.match(behavior, /data-related-carousel/);
assert.match(behavior, /relatedTrack\.append\(relatedTrack\.firstElementChild\)/);
assert.match(behavior, /relatedTrack\.prepend\(relatedTrack\.lastElementChild\)/);
assert.doesNotMatch(behavior, /carouselClone/);

console.log('Automatic article-page tests passed.');
